logging:
  log-level: DEBUG

pipelines:
  active-pipeline: google-cloud
  local:
    input: so-dump/Posts.xml
    output: output/Posts.jsonl
    pipeline-options:
      runner: DirectRunner
  google-cloud:
    input: gs://sotorrent_pipeline/so-dump/Posts.xml
    output: gs://sotorrent_pipeline/output/Posts.jsonl
    bigquery-schema-dir: bigquery_schemas
    pipeline-options:
      runner: DataflowRunner
      project: sotorrent-org
      region: us-central1
      job-name: sotorrent-pipeline-test
