logging:
  log-level: DEBUG

google-cloud:
  input_bucket: sotorrent_pipeline_input
  pipeline-options:
    runner: DataflowRunner
    project: sotorrent-org
    bucket: sotorrent
    temp_location: gs://sotorrent_pipeline_temp
    output: gs://sotorrent_pipeline_output
    region: us-central1
    job_name: so-dump-import
  schema_dir: schema
  key_file: google-cloud-key.json
